import Head from 'next/head'
import Image from 'next/image'

import bgImage from '@/components/assets/background/LeftPattern.png'
import UserLogin from '@/components/form/LoginForm/Login'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Image src={bgImage} alt={'Bg'} width={540} />
        <UserLogin />
      </main>
    </>
  )
}
